### PR TITLE
updated dependencies for Gatsby v3

### PR DESCRIPTION
**Pull request by dan-mba**
Fixes issue #57 

I updated the package.json  files for all non-experimantal packages and the basic samples.
I couldn't update all the dev dependencies for gatsby-material-ui-components because when I did it ran into weird typescript errors.

I ran `yarn test` and it passed.

I tried to run `yarn start:simple` but it fails.
I think this might be related to yarn workspaces, but since I don't normally use yarn, I'm not sure how it picks up the packages.

### CODE REVIEW

**Comment by dan-mba** [comment]
Gatsby v3 requires node 12 at a minimum

**Comment by hupe1980** [comment]
@dan-mba I just updated the Node Version in the ci

**Comment by hupe1980** [comment]
@dan-mba  "_I tried to run yarn start:simple but it fails._"  -> The gatsby version in www is still version 2. Therefore there is a version conflict in monorepo

**Comment by dan-mba** [comment]
The www directory is dependent on gatsby-theme-netlify-cms which is currently incompatible with gatsby v3.

I can rollback the changes to that package.json, but will that still leave the monorepo with incompatible versions?

**Comment by hupe1980** [comment]
You can comment out the theme gatsby-theme-netlify-cms. This is not really in use at the moment

**Review by hupe1980 — APPROVED** [review]
LGTM! Thx

**Pull request merged**
